Diretorios
linkjr-castanhal/linkjr pull request #24
Opened 2024-12-07 00:13 UTC by Medeiros20

2024-12-07 16:26 UTC, ecsistem requested changes
@Medeiros20   Remove o default 

Usa o 
```
export function NomeDaFuncao(){
return(
<>
<h1>Nome da Pagina </h1>
</>
)
}
```
Por que evitar export default e preferir export nomeados?
    Clareza e Consistência no Nome
    Com export default, você pode importar o componente com qualquer nome, o que pode causar inconsistências no código.
    Por exemplo:

// Usando default
```
import MinhaPagina from './Pagina'; 
import OutraPagina from './Pagina'; // Mesmo componente, nome diferente

```
Já com export nomeados, o nome é fixo, o que reduz ambiguidades:

`import { NomeDaFuncao } from './Pagina';`

Melhora a Refatoração
Se você renomear o componente ou função declarada, as IDEs e ferramentas como o TypeScript conseguem rastrear e corrigir automaticamente todas as referências.
Com export default, isso pode ser perdido, pois o nome usado na importação é arbitrário.

Facilita a Identificação de Erros
Ao usar export default, erros como um typo no nome da importação não são detectados facilmente:

`import MihaPagina from './Pagina'; // Erro despercebido`

Usando export nomeados, qualquer erro na importação será capturado imediatamente:

`import { NomDaFuncao } from './Pagina'; // Erro detectado`

Melhor para Colaboração em Equipe
Em projetos com várias pessoas, os export nomeados tornam o código mais fácil de entender e rastrear. Todos sabem exatamente qual é o nome original do componente.

Maior Consistência em Imports e Exports
No padrão export nomeado, todos os componentes são exportados de forma explícita e consistente, facilitando a manutenção:

```
export function Header() { ... }
export function Footer() { ... }
export function Sidebar() { ... }
```

Compatibilidade com Ferramentas de Árvore de Dependências (Tree Shaking)
Embora export default também seja compatível com tree shaking, o uso de export nomeados é mais explícito e menos propenso a erros em projetos maiores.

2024-12-07 16:34 UTC, ecsistem commented
@Medeiros20 lembra de rodar no teu terminal o comando:
`npm run lint`
e o 
`npm run build`

Para confirmar se está tudo ok

2024-12-08 11:00 UTC, ecsistem commented
@Medeiros20 faltou remover o default

2024-12-08 17:43 UTC, Medeiros20 commented
@ecsistem Quando eu tiro o default das funções aparece um erro nas page.ts. acho que eu não entedi direito

2024-12-09 00:54 UTC, merged

2024-12-09 00:55 UTC, ecsistem reviewed
LGTM 
@Medeiros20 removi os prettier ignore